[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[[headers]]
  for = "/*.apdu"
  [headers.values]
    Content-Type = "text/plain"

[[redirects]]
  from = "/minimal.html"
  to = "/minimal.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/create-account.html"
  status = 200
